### ISSUE TITLE
Object.fromEntriesの記事の日付が未来

### ISSUE THREAD

**Issue by myakura** [yuheiy/yuheiy.com-v6#1]
https://github.com/yuheiy/yuheiy.com-v6/blob/15e12676624be77cf611514f3d425f0e54cb5c1a/src/content/blog/2024-03-06-object-from-entries.mdx#L3

10日ほど先の日付になっているようです。

**Comment by yuheiy** [comment]
@myakura 修正しました。ご指摘ありがとうございます！
